version: '3.4'

services:
  transactionalscripttodo:
    image: ${DOCKER_REGISTRY-}transactionalscripttodo
    build:
      context: .
      dockerfile: TransactionalScriptToDo/Dockerfile
  database:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Str0ngP455W0RD